mindmap  
  root((DocHub))
      (0. Глосарий терминов)
      (1. Архитектурные принципы и стандарты)
          1. Архитектурные принципы
          2. Архитектурные стандарты
              1. Стандарты мониторинга
              2. Стандарты кибербезопасности
          3. Стандарты по платформам
              1. DocHub
              2. S платформы
              3. Платформа 1C
              4. Платформа MS Dynamics
              5. Apach Kafka
      (2. Architecture decision log)
      (3. Информационная архитектура)
          1. Бизнес сущности
          2. Список бизнес сущностей в системах
      (4. Развитие корп архитектуры)
          1. Политики и архитектурные процессы            
          2. Инструменты
              1. DocHub
                  1. Руководство по описанию прикладной архитектуры
                  2. Структура системы или сервиса описанного в DocHub
                  3. Интеграционная схема выгрузки систем
                  4. Примеры запросов JSONata
              2. Storm BPMN
                  1. Описание нюансов работы в ГК Самолет
          3. Команды
          4. План развития
      (5. Прикладная архитектура)
          1. Список систем
          2. Карта приложений
          3. Верхнеуровневый прикладной ландшафт ПА/L1
          4. Детальная документация систем ПА/L1
          5. Детальная архитектуры систем ПА/L2
          6. Детальная документация систем ПА/L2
          7. Функционал систем
          8. Graph систем
      (6. Технологическая архитектура)
      (10. Бизнес архитектура)
          1. Карта процессов
      (20. Техрадар)
      (90. Структура меню)
      (91. Проблемы)
